### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by mishantrop** [sam3d/vue-svg#20]
`vue-cli-plugin-svg@0.2.1`

```
~/projects/xxx/frontend  npm run start                                                                                   ✔  4s 

> talan-frontend@1.1.0 start
> vue-cli-service serve

 INFO  Starting development server...
 ERROR  TypeError: Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at setup (/home/user/projects/xxx/frontend/node_modules/vue-cli-plugin-svg/index.js:44:41)
    at /home/user/projects/xxx/frontend/node_modules/vue-cli-plugin-svg/index.js:22:30
    at /home/user/projects/xxx/frontend/node_modules/@vue/cli-service/lib/Service.js:252:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/home/user/projects/xxx/frontend/node_modules/@vue/cli-service/lib/Service.js:252:26)
    at Service.resolveWebpackConfig (/home/user/projects/xxx/frontend/node_modules/@vue/cli-service/lib/Service.js:256:48)
    at PluginAPI.resolveWebpackConfig (/home/user/projects/xxx/frontend/node_modules/@vue/cli-service/lib/PluginAPI.js:132:25)
    at serve (/home/user/projects/xxx/frontend/node_modules/@vue/cli-service/lib/commands/serve.js:73:31)
    at Service.run (/home/user/projects/xxx/frontend/node_modules/@vue/cli-service/lib/Service.js:246:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

 ~/projects/xxx/frontend  master !17  vue inspect --rules                                                                           1 ✘  3s 
 ERROR  TypeError: Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at setup (/home/user/projects/xxx/frontend/node_modules/vue-cli-plugin-svg/index.js:44:41)
    at /home/user/projects/xxx/frontend/node_modules/vue-cli-plugin-svg/index.js:22:30
    at /home/user/projects/xxx/frontend/node_modules/@vue/cli-service/lib/Service.js:252:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/home/user/projects/xxx/frontend/node_modules/@vue/cli-service/lib/Service.js:252:26)
    at Service.resolveWebpackConfig (/home/user/projects/xxx/frontend/node_modules/@vue/cli-service/lib/Service.js:256:48)
    at PluginAPI.resolveWebpackConfig (/home/user/projects/xxx/frontend/node_modules/@vue/cli-service/lib/PluginAPI.js:132:25)
    at /home/user/projects/xxx/frontend/node_modules/@vue/cli-service/lib/commands/inspect.js:21:26
    at Service.run (/home/user/projects/xxx/frontend/node_modules/@vue/cli-service/lib/Service.js:246:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

```

`package.json`
```
{
  "dependencies": {
    "babel-eslint": "10.1.0",
    "core-js": "3.19.1",
    "sass": "1.43.4",
    "sass-loader": "10.2.0",
    "tslib": "2.3.1",
    "typescript": "4.4.4",
    "vue": "3.2.11",
    "vue-class-component": "8.0.0-rc.1",
    "vue-loader-v16": "16.0.0-beta.5.4",
    "vuex": "4.0.2"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "5.3.1",
    "@typescript-eslint/parser": "5.3.1",
    "@vue/cli-plugin-babel": "5.0.0-beta.6",
    "@vue/cli-plugin-eslint": "5.0.0-beta.6",
    "@vue/cli-plugin-typescript": "5.0.0-beta.6",
    "@vue/cli-service": "5.0.0-beta.7",
    "@vue/compiler-sfc": "3.2.21",
    "@vue/eslint-config-typescript": "9.0.1",
    "eslint": "8.2.0",
    "eslint-plugin-vue": "8.0.3",
    "vue-cli-plugin-svg": "~0.2.1",
    "vue-eslint-parser": "8.0.1"
  },
}
```

**Comment by LuaxY** [comment]
Same issue here, @mishantrop did you find a solution?

**Comment by Vl4dimyr** [comment]
I got the same issue as well. Hope this will be fixed soon! For now I switched to https://www.npmjs.com/package/vue-svg-inline-loader hope that helps anyone here...

**Comment by mits87** [comment]
Same issue here :/

**Comment by lukastillmann** [comment]
Yeah, me too

**Comment by LuaxY** [comment]
I switch to [vue-svg-inline-loader](https://www.npmjs.com/package/vue-svg-inline-loader) like mentionned by @Vl4dimyr

**Comment by rene-mueller** [comment]
[vue-svg-inline-loader](https://www.npmjs.com/package/vue-svg-inline-loader) does not work for me because the problem is that the following method of use does not work: https://github.com/oliverfindl/vue-svg-inline-loader/issues/2
